### PR TITLE
#161123994 Create store manager app menu

### PR DESCRIPTION
**Pull request by Teatoller**
# #161123994 Creates a StoreManagerApp Menu/Dashboard

## What does this PR do?
* It creates a landing page after login, where a Store Attendant can _access_ a link to view only **Store Attendant Path**.

storemanagerapp landing pg _(Admin button not active it is for another feature branch)
* A button that links Store Attendant to an interface where they can _access view only _ **Reports.**

storemanagerappreportbtn

* A button that links Sore Attendant to an interface where they can _search items by_ **Product Name.** 

smaviewonlyproduct

* A button that links Store Attendant to an interface where they can _search product_ by **Product Category**
smavwonlybycartegory

* A button that links Store Attendant to an interface where they can _search product_ by **Product Barcode**

smavwbybarcode

* A button that links Store Attendant to an interface where they can _search product_ by **Product Type**. _Type being mode of payment (cash, card, mpesa, voucher.)_

smavwonlytypesale

* A button that links Store Attendant to an interface where they can _search product_ by **Store Attendant Id**.  _In this scenario modeled as  (A1234) but can be anything standardized._

smavwonlybyattendantid

* A button that links Store Attendant to an interface where they can _search product_ by **Date & Time**.  _(Date & Time of transaction)_

smavwbydate

* A button that links Store Attendant to an interface where they can _search product_ by **Receipt/Bill Number**.

smavwbillno

## The Store Attendant is able to search product by;
*Here the Store Attendant has the button with links to view only sales records. The pages have no _Edit_ or _Delete_ or _Modify_ buttons.

1. Product Name
2. Product Category.
3. Product Barcode.
4. Product Date & Time of Sale.
5 Product by type of sale.
6. Product by Store Attendant.
7. Product by Receipt or Bill no of a transaction.

## Description of the tasks completed
*I created a Store Manager PVT user story which generated a unique ID #161123994.
link: https://www.pivotaltracker.com/n/projects/2203439
*I created a  feature branch (ft-create-storeManagerApp-menu-161123994) off the 'gh-pages branch'.
*I created HTML files in the UI directory and updated the style.css file CSS. The HTML file names hint at their purpose the page is intended to achieve.
*I made commits at suitable intervals as I built the project allowing it to be segmented into sub-modules and pushing to GitHub using Git.
### The PR can ve viewed at;
GIthub Link: https://github.com/Teatoller/StoreManagerApp/pull/2

### CODE REVIEW

**Comment by jomasim** [comment]
i like the UI. Note:
- I would like you to check on the choice of the colors

**Comment by Paulvitalis200** [comment]
Awesome UI.. on the color. I don't think blue goes well with brown.. and what about using a white color for your text?

**Comment by scott-kenya** [comment]
You are on the money

**Comment by vmuthabuku** [comment]
neat UI interface

**Comment by Teatoller** [comment]
> i like the UI. Note:
> 
> * I would like you to check on the choice of the colors

Thank you Jomasin for taking the time to spare.
I will concur the blue is quite off. 

Regards
Steven Ennis

**Comment by Teatoller** [comment]
> Awesome UI.. on the color. I don't think blue goes well with brown.. and what about using a white color for your text?

Hi PaulStar200,
Thank you for the feedback. I am making amends.
Regards

**Comment by Teatoller** [comment]
> You are on the money

HelloScott 
Thank you very much.
Seems you would have been a satisfied client.

Regards
Steven Ennis

**Comment by Teatoller** [comment]
> neat UI interface

Hello Vmathabuku,
Thank you for the feedback and taking time to give me valued encouraging feedback.

Regards
Steven Ennis

**Pull request merged**
