### PR TITLE
#161167178 View All Products and Qty Optimization Levels 

### PR DESCRIPTION
**Pull request by Teatoller**
# Title : #161167178 Store Inventory Balances

##What does this PR do?
This PR creates a profile where a Store Attendant and Store Manager (Admin) can view the status of product levels in the store.

* The User can search by *Product Name* 
 
smaqtybyproduct

* The User can search by *Product Category* 
smaqtybycartegort

* Data Presented by the two reports comprise of;
1. Opening Stock.
2. Minimum Stock.
3. Closing Stock(Base Stock)
4. Available stock.(Yes/No) ~1/0
5. Product Name.
6. Product Barcode.
7. Product Category.

It provides information  which can enable the User to take appropriate action in their replenishment cycles and stock Management.

## What I Did to achieve this.

* I used a nuber of HTML pages and tags.
* I resourced the internet for relevant informatin where I had blockers.
* On the feature branch detailed (ft-View-Stock-Balances-161167178), I made commits at suitable intervals and pushing to Github account.
* I used a modularised approach in building my pages. 

To view PVT story;
https://www.pivotaltracker.com/n/projects/2203439

### CODE REVIEW

**Comment by Paulvitalis200** [comment]
This is good and descriptive.

**Comment by Deekerubo** [comment]
I like the layout of your UI, probably where you have used green and purple you should make the colors a bit darker to match the page theme. Otherwise your UI is eye catching.

**Comment by Teatoller** [comment]
> This is good and descriptive.

Thank you very much @Paulstar200

**Comment by Teatoller** [comment]
> I like the layout of your UI, probably where you have used green and purple you should make the colors a bit darker to match the page theme. Otherwise your UI is eye catching.

Thank you @Deekerubo , I will improve it with your suggestion.

Regards
Steven Ennis

**Pull request merged**
