### PR TITLE
#161087619 Creates a User log-in portal

### PR DESCRIPTION
**Pull request by Teatoller**
#  #161087619 Creates a User login portal

##What does this PR do?

* Enables a store attendant or Admin(Store manager), be able to have a User Interface where they can log in and gain access to the application.

* It expects a user to have an email (preferably the entity's official mail address.
* Validate the login with a password.
* Be able to Exit the active StoreManager login interface to a screen saver.

## Description of the tasks completed

* I created a Store Manager PVT user story which generated a unique ID[#161087619].
* I created a repo 'StoreManager on Github with a README.md file which I then cloned to my local machine.
* I integrated PVT and my Github account.
* I created a gh-pages branch and on it a feature branch (ft-user-login-page-161087619).

I created a UI directory and in it a CSS & image folder.
* Added a login.html page
* identified a suitable logo for my app and saved in the image.
* Built the login page on the feature branch detailed about making commits at suitable intervals and pushing to Github account.

 ## To view the code use the link provided.
 https://github.com/Teatoller/StoreManagerApp/compare/gh-pages...ft-user-login-page-161087619
 
 ## To view PVT story;
 https:https://www.pivotaltracker.com/n/projects/2203439

### CODE REVIEW

**Comment by Teatoller** [comment]
Image of log in interface:
storemanagerapp 2018-10-10 08-08-09

**Comment by Teatoller** [comment]
Login screen saver
screensaver 2018-10-10 09-50-11

**Comment by Deekerubo** [comment]
Change the title for this PR to `#ID topic` the interface looks good

**Comment by Teatoller** [comment]
> Change the title for this PR to `#ID topic` the interface looks good

Thank you Diana. I have implemented the feedback. 
Did I implement it correctly?

**Comment by Paulvitalis200** [comment]
Good. Consistent color

**Pull request merged**
